### PR TITLE
add exclusion for schematic type into get_all_resources

### PR DESCRIPTION
**Pull request by 9strands**
Attempting to fix current failures on the sandbox-deletion, preventing release of some cleaned sandboxes.

@stencell - can you take a look?

### CODE REVIEW

**Comment by 9strands** [comment]
Updated with fixes from @stencell

**Comment by 9strands** [comment]
Running test at the moment.

**Review by stencell — APPROVED** [review]

**Comment by 9strands** [comment]
still needs work - not ready to merge, yet.

**Comment by 9strands** [comment]
Added negation to clean the list of the items in the ignore list.  

Test of negation here:
```
>>> resource_list = ['security-advisor','schematics','testme','other_resource']
>>> ignore_resource = ['security-advisor', 'schematics']
>>> resource_list
['security-advisor', 'schematics', 'testme', 'other_resource']
>>> response = [res for res in resource_list if not any(
... ig in res for ig in ignore_resource)]
>>> response
['testme', 'other_resource']
>>> 
```

**Comment by 9strands** [comment]
@jkupferer - can you take a look and see if this is good to merge as-is?

**Review by thomas-crowe — APPROVED** [review]

**Pull request merged**
